name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "firebase_service_key.json"
        json: ${{ secrets.FIREBASE_ADMIN_SDK }}
        dir: src/main/resources


    ## create application.yml
    - name: make application.yml
      run: |
        ## create application.yml
        cd ./src/main/resources
        
        ## apple key 파일 생성
        touch ./apple_secret.p8

        # application.yml 파일 생성
        rm ./application.yml
        touch ./application.yml
        
        # data sql 파일 생성
        touch ./data.sql

        # apple key 쓰기
        echo "${{ secrets.APPLE_SECRET_KEY }}" >> ./apple_secret.p8
        
        # data sql 파일 쓰기
        echo "${{ secrets.DEV_DATA_SQL }}" >> ./data.sql
        
        # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION_DEV }}" >> ./application.yml

      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew bootJar

    ## 웹 이미지 빌드 및 도커허브에 push
    - name: API Dockerfile 빌드 후 Docker Hub push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/niceguy-api .
        docker push ${{ secrets.DOCKER_REPO }}/niceguy-api

    ## docker compose up
    - name: DEV 서버 docker-compose 실행 (SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker rm -f $(docker ps -qa)
          docker pull ${{ secrets.DOCKER_REPO }}/niceguy-api
          docker-compose run -d -p 8081:8080 dev
          docker image prune -f

    - name: action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Juwon Lee
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      if: always() # Pick up events even if the job fails or is canceled.