name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    ## create application-database.yaml
    - name: make application-dev.yml
      run: |
        ## create application-dev.yml
        cd ./src/main/resources

        # application-dev.yaml 파일 생성
        touch ./application-dev.yml

        # GitHub-Actions 에서 설정한 값을 application-dev.yml 파일에 쓰기
        echo "${{ secrets.APPLICATION_DEV }}" >> ./application-dev.yml
      shell: bash

    ## gradle build
    - name: Build with Gradle
      run: ./gradlew bootJar


    ## 웹 이미지 빌드 및 도커허브에 push
    - name: API docker build and push
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/niceguy-api .
        docker push ${{ secrets.DOCKER_REPO }}/niceguy-api

    ## docker compose up
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_HOST }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        script: |
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull ${{ secrets.DOCKER_REPO }}/niceguy-api
          docker-compose up -d
          docker image prune -f